services:
  emoncms:
    image: alexjunk/emoncms:alpine3.18_emoncms11.4.11
    volumes:
      - /data:/data
    environment:
      - TZ=Europe/Paris
      - REDIS_BUFFER=1 # 0 to disable low-write mode
      - EMONCMS_LOG_LEVEL=2 # 1=INFO, 2=WARN, 3=ERROR
      - MYSQL_DATABASE=emoncms
      - MYSQL_USER=emoncms
      - MYSQL_PASSWORD=emonpiemoncmsmysql2016
      - MQTT_USER=emonpi
      - MQTT_PASSWORD=emonpimqtt2016
      - MQTT_HOST=localhost
      - MQTT_LOG_LEVEL=error
      - CRT_FILE=/etc/ssl/apache2/server.pem
      - KEY_FILE=/etc/ssl/apache2/server.key
      - CNAME=localhost
    ports:
       # These ports are in format <host-port>:<container-port>
      - 7443:443 # Public HTTPS Port 
      - 8081:80 # Public HTTP Port
      - 9883:1883 # Public MQTT Port (if using the internal broker)
    restart: always
